[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
live_config_reload = true

[window]
padding = { x = 12, y = 10 }
decorations = "full"
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Windowed"
dynamic_title = true

[font]
size = 16
offset = { x = 0, y = 4 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[scrolling]
history = 10000

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]
draw_bold_text_with_bright_colors = true

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
